### ISSUE TITLE
AttributeError: module 'soltrannet' has no attribute 'predict'

### ISSUE THREAD

**Issue by xavierchee** [gnina/SolTranNet#3]
Good morning, everything was working fine for the past few weeks but suddenly i had this issue when i was using SolTranNet. 
Re-installing did not help. 

Traceback (most recent call last):
  File "./soltrannet_solubility_predictor.py", line 12, in <module>
    predictions = [str(prediction[0]) for prediction in stn.predict(smiles)]
AttributeError: module 'soltrannet' has no attribute 'predict'

I ran the tutorial codes on Github but received similar issues
Failed to calculate solubility for SMILES: c1ccccc1 - module 'soltrannet' has no attribute 'predict'
Failed to calculate solubility for SMILES: c1ccccc1 .ignore - module 'soltrannet' has no attribute 'predict'
Failed to calculate solubility for SMILES: Cn1cnc2n(C)c(=O)n(C)c(=O)c12 - module 'soltrannet' has no attribute 'predict'
Failed to calculate solubility for SMILES: [Zn+2] - module 'soltrannet' has no attribute 'predict'
Failed to calculate solubility for SMILES: [Na+].[Cl-] - module 'soltrannet' has no attribute 'predict'

Thanks!

**Comment by francoep** [comment]
I am confused, as there is no file "soltrannet_solubility_predictor.py"  in the code base.

It seems from the AttributeError that soltrannet is unable to find the predict for some reason. Please indicate your python version, cuda version, operating system, pytorch version, etc. of your environment.

**Comment by xavierchee** [comment]
Hi Paul, the soltrannet_solubility_predictor.py is my own code. Nonetheless, you can see that it uses the same syntax as the code on GitHub `predictions = [str(prediction[0]) for prediction in stn.predict(smiles)`

```
import soltrannet as stn

# Get input and output file names from user
smiles_file = input("Enter the input file name: ")
output_file = input("Enter the output file name: ")

# Read SMILES from file
with open(smiles_file, "r") as file:
    smiles = [line.strip() for line in file]

# Perform predictions
predictions = [str(prediction[0]) for prediction in stn.predict(smiles)]

# Save predictions to file
with open(output_file, "w") as file:
    file.write("\n".join(predictions))

print("Predictions saved to", output_file)
```

**Comment by xavierchee** [comment]
Thanks Paul.
Python version: 3.10.4
Cuda version: None 
Operating system: Linux farnarkle1 4.18.0-477.15.1.el8_8.x86_64 (This is on a supercomputer called Ozstar) 
Pytorch version: 2.0.1+cu117
Anaconda: anaconda3/2021.05

**Comment by dkoes** [comment]
It is very strange for stn.predict not to be defined.  What is the output of `dir(stn)` and `stn.__path__` (the later should be the soltrannet installation location).

**Comment by xavierchee** [comment]
**dir(stn) output** 
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'argparse', 'calculate_solubility', 'main', 'read_database', 'stn']

**stn.__path__** 
I did the following command `pip show soltrannet`

Name: soltrannet
Version: 1.0.0
Summary: Molecule attention transformer for predicting aqueous solubility (log S)
Home-page: https://github.com/gnina/SolTranNet
Author: Paul Francoeur
Author-email:
License: UNKNOWN
Location: /home/xchee/.local/lib/python3.10/site-packages
Requires: pathlib, torch
Required-by:

**Comment by xavierchee** [comment]
Thanks very much Prof David and Francis, i really loved using this tool and it's just annoying that it didn't work this morning. I tried re-installing but to no avail. Really hope i can get it up and running again, so i really appreciate both your help. Thanks for your time.

**Comment by xavierchee** [comment]
I tried to force reinstall soltrannet using` pip install --force-reinstall soltrannet` but still has the missing predict function. 

**dir(stn)** showed the following

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'argparse', 'calculate_solubility', 'main', 'read_database', 'stn']

**Comment by dkoes** [comment]
It would be great if you could check the value of `stn.__path__` like I asked.  I suspect you have a soltranet.py file in the current directory and that is what is getting imported instead of the installed package.

**Comment by xavierchee** [comment]
Thanks prof. Would you mind explaining how i could check the value for stn.__path__? Apologies for my ignorance.

**Comment by francoep** [comment]
import the package and print the value, such as below

import soltrannet as stn
print(stn.\_\_path\_\_)

Edit: markdown messing with my typing that I didn't preview to double check about

**Comment by dkoes** [comment]
I am not asking for `stn.path`, I am asking for  `stn.__path__`

**Comment by xavierchee** [comment]
Hi all, if i do 

import soltrannet as stn
print(stn.__path__) 

i get the following error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'soltrannet' has no attribute '__path__'. Did you mean: '__name__'?

**Comment by dkoes** [comment]
If `__path__` doesn’t work, try `__file__`. The point is you almost certainly are not importing the installed package and you want to find out what you are importing (probably a file in the current directory).

**Comment by xavierchee** [comment]
Hi Prof David and Francis, thanks again for your help! 
Prof David, your hunch about accidentally importing a file in the current directory was correct! 
After i amended the culprit file, it worked like a charm. 

Thank you for your patience!
